### ISSUE TITLE
Tiny bug: printing a OpenSCAD object chops the rest of the printout

### ISSUE THREAD

**Issue by gandrewstone** [gsohler/openscad#17]
**Describe the bug**

printing out an openscad object appears to be chopping the rest of the line:

```
prefix None suffix
prefix OpenSCAD (2)
```

**To Reproduce**
try this:
```
import openscad as ops
s = ops.sphere(10)
t = None
print("prefix", t, "suffix")
print("prefix", s, "suffix")
```

**Comment by gsohler** [comment]
__repr__ member of openscad object created an extra '\0' character.
Could you check if its fixed in your place and close ?

**Comment by gandrewstone** [comment]
got this error building e1f34aab6c77300629b4ae6eb68edfc156813e42
/usr/bin/ld: CMakeFiles/OpenSCAD.dir/src/geometry/GeometryEvaluator.cc.o: in function `std::ostream& operator<< <__mpz_struct [1], __mpz_struct [1]>(std::ostream&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]> const&)':
GeometryEvaluator.cc:(.text._ZlsIA1_12__mpz_structS1_ERSoS2_RK10__gmp_exprIT_T0_E[_ZlsIA1_12__mpz_structS1_ERSoS2_RK10__gmp_exprIT_T0_E]+0x36): undefined reference to `operator<<(std::ostream&, __mpz_struct const*)'

**Comment by gsohler** [comment]
Sorry, cannot See this Error in my Side. Did you try a "make clean" ?


Andrew Stone ***@***.***> schrieb am Sa., 17. Feb. 2024,
17:05:

**Comment by gandrewstone** [comment]
no trying that now; I was able to build HEAD~1 fine though
