### ISSUE TITLE
Is rotate(degrees, axis) supported?

### ISSUE THREAD

**Issue by gandrewstone** [gsohler/openscad#18]
**Is your feature request related to a problem? Please describe.**

openscad language supports rotation around an arbitrary axis

**Describe the solution you'd like**
API for rotation around an arbitrary axis

import openscad as ops
tcube = ops.cube([10,10,10])
tc = tcube.rotate(45, [10,10,0])
output(tc)

**Comment by gsohler** [comment]
yes, its missing, will supply ASAP

**Comment by gsohler** [comment]
now the missed feature is there to comply with SCAD language.
Let me check if its working for you, I was missing it myself ;)
