### ISSUE TITLE
cylinder (actually cone) parameter problem

### ISSUE THREAD

**Issue by gandrewstone** [gsohler/openscad#19]
**Describe the bug**
Creating a cone (5 parameter cylinder) appears to ignore the 2nd parameter.
It appears to make a cone whose top is radius 1 regardless of the parameter

**To Reproduce**
```
from openscad import *
s = cylinder(10,5,5,True)
output(s)
```

The above makes a cone, but really since the top and bottom diameters are =, we should get a cylinder.

**Expected behavior**
output equivalent to:
```
cylinder(10,5,5, true);
```

**Comment by gsohler** [comment]
should be fixed, please check
