### ISSUE TITLE
Apple Silicon Binaries

### ISSUE THREAD

**Issue by gsrunion** [gsohler/openscad#23]
Per the title, it appears the provided installer is for Intel silicon. When running the binary installed via that method...

% ./OpenSCAD
zsh: illegal hardware instruction  ./OpenSCAD

Consider provided Apple silicon compatible builds to aid adoption......if you PR to OpenSCAD mainline is delayed any further.

**Comment by gsohler** [comment]
Hi,
Thank you for testing
Unfortunately I don't own a MAC myself and I got the chance to borrow one
some time back, which i real old one
and its apparently not compatible with recent models.
But I am Very interested in generating OpenSCAD images for recent macs.
All Volunteers are welcome, I can offer help giving hints for issues which
arise during compilation.

**Comment by gsohler** [comment]
If somebody would grant me temporary user-only access to an apple-silicon mac, I would  try my best to compile pythonscad there and create a DMG file.

**Comment by gsohler** [comment]
A Macbook having processor M1, M2, or M3 means its running on Apple Silicon, right ?

**Comment by gsohler** [comment]
Today I have created a new Apple Disc image onto pythonscad.org
Almost all python features are there, let me know if its working

**Comment by gsrunion** [comment]
Oooh I look forward to having a look.

Regards,
    Steve Runion

**Comment by gsohler** [comment]
Latest Apple Silicon Binaries (2024-08-08) are reported working
