### ISSUE TITLE
Possible to have more informative error messages?

### ISSUE THREAD

**Issue by WillAdams** [gsohler/openscad#31]
If one has a very basic Python file such as:

    #!/usr/bin/env python

    def psettool(tn):
        global currenttool
        currenttool = tn
    
    def pcurrent_tool():
        global currenttool
        return currenttool

which is loaded in:

    use <gcptest.py>;
    
    /* [CAM] */
    small_square_tool_no = 122; // [0:0,122:122,112:112,102:102]
    
    psettool(small_square_tool_no);
    
    echo(str(pcurrent_tool()));
    echo(str(pcurrent_tool(small_square_tool_no)));

Then the last line will generate the error:

[WARNING: Ignoring unknown function 'pcurrent_tool' in file gcptest.scad, line 9](https://github.com/gsohler/openscad/issues/8,C:/Users/willa/OneDrive/Desktop/gcptest.scad)

which is quite confusing to a naïve programmer --- would it be possible to have the message instead explain that the function was not called correctly?

**Comment by gsohler** [comment]
yes, confirmed error.
the message should rather say, that neither a python function nor a openscad function could be called.

**Comment by gsohler** [comment]
Today I was working on better error handling.
Now pythonscad is able to display

* when there is a general parsing error in the python file (and which)
* if neither such a python nor scad module is found
* if there is a parameter mismatch in the called python function (and which)
* if there is an error during evaluatin of the python function(and which)

I have released 09-23 today. 
Let me know if error handling is missing some "features"

**Comment by WillAdams** [comment]
Nice!

![image](https://github.com/user-attachments/assets/a2f23168-0b2f-4488-b783-f0dd5a25a69b)

I'll keep an eye out for messages which don't make sense to me and keep you posted.

**Comment by gsohler** [comment]
This only happens with the windows distribution and the error happens in the python3.11.dll
Right now I dont know, how to address it
(same story: you cannot import ctypes lib in PythonSCAD under windows)
