### ISSUE TITLE
8.10 AppImage crashes on Arch Linux with simple file containing only a sphere

### ISSUE THREAD

**Issue by gatesphere** [gsohler/openscad#36]
**Describe the bug**
The AppImage crashes on my Arch Linux install after running this file:

```
from openscad import *
sphere().output()
```

I get a segmentation fault.  If the file contains this code, it will crash when loading the file, again with a segmentation fault.

If I provide a value for r, (i.e. `sphere(r=1)`), the crash does not occur.  I suspect this to be an issue with the default values for sphere.

**To Reproduce**
  1. create a .py file with the above contents
  2. load it into PythonSCAD

**Expected behavior**
No crash -- default values for sphere applied appropriately

**Code reproducing the issue**
```
from openscad import *
sphere().output()
```

**Screenshots**
N/A

**Environment and Version info (please complete the following information):**
 - OS: Arch Linux, with Python 3.11 installed via AUR package `python311` (only way to get the AppImage to run)
 - System: Ryzen 5 3500 U
 - PythonSCAD 8.10 AppImage from PythonSCAD.org

**Library & Graphics card information**
N/A

**Additional context**
N/A

**Comment by gsohler** [comment]
gatesphere, you are absolutely correct.
I found the bug when trying sphere(d=2)
r was not initialized either and PyList_Size(nullptr) is not a good idea.
fixed already recently. 
The bug will quite likely disappear when I manage to create a new AppImage from the latest sources.
Thank you!
