### ISSUE TITLE
Allow editor to get current python state

### ISSUE THREAD

**Issue by Matthieu-LAURENT39** [gsohler/openscad#4]
The text editor currently has no way of knowing if python is currently active (i.e. python is enabled and the current file is a python file).
If the editor had that knowledge, it would allow to add much better editing features.

Having a `python_enabled` public attribute on the ScintillaEditor class could do the trick, however i'm not too sure how python mode is actually toggled (it seems like it's computed from the file name every time?), so i can't really add it myself

**Comment by Matthieu-LAURENT39** [comment]
I implemented this by allowing ScintillaEditor to access MainWindows's python_active attribute, however i didn't get time to test it, and compilation is taking too long.
I'll test it tomorrow and submit a PR.

**Comment by gsohler** [comment]
remarkably compilation is only fast 1st time and slow later.
to get make the boost, do
make clean
make

**Comment by Matthieu-LAURENT39** [comment]
It's the other way around for me, it's really slow the first time, then fast since it only recompiles the changed files

**Comment by Matthieu-LAURENT39** [comment]
This is implemented and works, i'll make a PR

**Comment by Matthieu-LAURENT39** [comment]
resolved in #6
