### ISSUE TITLE
New 10-06 crashes on .py file which worked in previous version

### ISSUE THREAD

**Issue by WillAdams** [gsohler/openscad#40]
Trying to work through re-writing, and had the attached file working in the previous version

[pythontest_one.zip](https://github.com/user-attachments/files/17272019/pythontest_one.zip)

but it crashes w/o any sort of error message in the new version which was just downloaded.

EDIT: It seems to crash on any .py file:

    #!/usr/bin/env python
    from openscad import *
    cube([1, 2, 3])

this is on Windows 11 after rebooting.

FURTHER EDIT: Even basic .scad files seem to crash:

    cube();

which is supposed to make a 1x1x1 cube crashes.

**Comment by gsohler** [comment]
New python locking appears not compatible  to windows. so I disabled it for windows.
New version 2024-10-07 is online and tested successfully
